

module.exports = {
  up: queryInterface => queryInterface.bulkInsert('courses', [
    {
      courseTitle: 'Facility Management Operations Training',
      memberFees: 108500.00,
      nonMemberFees: 115000.00,
      duration: 'Three Days',
      venue: 'IFMA Seceretariant',
      startDate: '10/9/2019',
      endDate: '10/11/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      courseTitle: 'Facility Management Strategy Class',
      memberFees: 125000.00,
      nonMemberFees: 135000.00,
      duration: 'Two Days',
      venue: 'IFMA Seceretariant',
      startDate: '11/7/2019',
      endDate: '11/8/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      courseTitle: 'Facility Maintenance Management',
      memberFees: 116000.00,
      nonMemberFees: 125000.00,
      duration: 'Two Days',
      venue: 'IFMA Seceretariant',
      startDate: '11/14/2019',
      endDate: '11/15/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      courseTitle: 'Facility Management Business Master Class',
      memberFees: 143500.00,
      nonMemberFees: 155000.00,
      duration: 'Three Days',
      venue: 'IFMA Seceretariant',
      startDate: '10/23/2018',
      endDate: '10/25/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      courseTitle: 'Workplace Productivity Training',
      memberFees: 106500.00,
      nonMemberFees: 115000.00,
      duration: 'Three Days',
      venue: 'IFMA Seceretariant',
      startDate: '9/11/2019',
      endDate: '9/13/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      courseTitle: 'Facility Project Managers',
      memberFees: 111000.00,
      nonMemberFees: 201000.00,
      duration: 'Two Days',
      venue: 'IFMA Seceretariant',
      startDate: '9/18/2019',
      endDate: '9/19/2019',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ], {}),

  down: queryInterface => queryInterface.bulkDelete('courses', null, {}),
};
